const mongoose=require("mongoose");
const Schema=mongoose.Schema;
const rfqpostSchema=new Schema({
   
      reference_no:{
          type:String,
      },
      product_name:{
          type:String,
      },
      product_details:{
          type:String,
      },
      dimension_length:{
          type:String,
      },
      D1unit:{
        type:String,
      },
      dimension_width:{
          type:String,
      },
      Dwunit:{
        type:String,
      },
      quantity_min:{
        type:String,
      },
      quantity_max:{
         type:String,
      },
      weight_min:{
          type:String,
      },
      W1unit:{
        type:String,
      },
      weight_max:{
         type:String,
      },
      Wwunit:{
        type:String,
      },
      buying_currency:{
          type:String,
      },
      buyprice_min:{
          type:String,
      },
      buyprice_max:{
          type:String,
      },
      expected_delivery_date:{
          type:String,
      },
      by_data:{
           type:String,
      },
      delivery_type:{
          type:String,
      },
      reference_no_expire:{
          type:String,
      },
      location:
      {
          type:String,
      },
      update_flag:
      {
          type:String,
      },
      delete_flag:{
          type:String,
      },
      customer: { type: Schema.Types.ObjectId, ref: 'requestforquotecustomers' },
      created_at:{
          type:String,          
      },
      updated_at:{
          type:String,
      }
});

module.exports = mongoose.model('requestforquote',rfqpostSchema);