'use strict';
const mongoose=require('mongoose');
const countrySchema=mongoose.Schema({
     _id:{
        type:mongoose.Schema.ObjectId,
        required:true,
      },
      id:
      {
         type:Number,
         required:true
      },
      name:
      {
         type:String,
         required:true,  
      },
      iso3:
      {
          type:String,
          required:true
      },
      iso2:
      {
        type:String,
        required:true
      },
      phonecode:
      {
          type:String,
          reuired:true
      },
      capital:
      {
          type:String,
          required:true
      },
      currency:
      {
          type:String,
          required:true
      },
      created_at:
      {
         type:Date,
         required:true
      },
      updated_at:
      {
        type:Date,
        required:true
      },
      flag:
      {
        type:Number,
        required:true
      },
      wikiDateId:
      {
          type:mongoose.Mixed,
          required:true,
      },
});
module.exports = mongoose.model('country',countrySchema);